export const TYPES = {
    UserService: Symbol('UserService'),
    UserRepository: Symbol('UserRepository'),
    UserController: Symbol('UserController'),
    UserTypeService: Symbol('UserTypeService'),
    UserTypeRepository: Symbol('UserTypeRepository'),
    UserTypeController: Symbol('UserTypeController'),
    UserProfileService: Symbol('UserProfileService'),
    UserProfileRepository: Symbol('UserProfileRepository'),
    UserProfileController: Symbol('UserProfileController'),
    UserPinService: Symbol('UserPinService'),
    UserPinRepository: Symbol('UserPinRepository'),
    UserPinController: Symbol('UserPinController'),
    UserPinHistoryService: Symbol('UserPinHistoryService'),
    UserPinHistoryRepository: Symbol('UserPinHistoryRepository'),
    UserPinHistoryController: Symbol('UserPinHistoryController'),
    VerificationCodeService: Symbol('VerificationCodeService'),
    VerificationCodeRepository: Symbol('VerificationCodeRepository'),
    VerificationCodeController: Symbol('VerificationCodeController'),
};